[tool.black]
line_length = 100
exclude = '(\.git|\.mypy_cache|venv)'
target_version = ["py39"]

[tool.isort]
skip = [".gitignore", ".dockerignore", "venv"]
combine_as_imports = true
include_trailing_comma = true
line_length = 100
multi_line_output = 3
reverse_relative = true
use_parentheses = true
